# Generated by Django 2.1.1 on 2018-09-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20180920_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='story_poits',
            new_name='story_points',
        ),
    ]
